USE ECOMMERCE;

INSERT INTO TEST_SCHEMACHANGE.ECOMMERCE.USER (NAME, ADDRESS)
    VALUES ('Jonas', 'No. 8 Main Stret');

INSERT INTO TEST_SCHEMACHANGE.ECOMMERCE.product (NAME, tagline)
    VALUES ('SHIRT', 'Collar Shirt');

INSERT INTO TEST_SCHEMACHANGE.ECOMMERCE.product (NAME, tagline)
    VALUES ('Jeans', 'JOHN PLAYERS JEANS'); 

INSERT INTO TEST_SCHEMACHANGE.ECOMMERCE.CART (USER_ID, product_id)
    VALUES (1, 1);       

