USE SCHEMA ECOMMERCE;
DROP TABLE IF EXISTS TEST_SCHEMACHANGE.ECOMMERCE.USER;
create or replace TABLE TEST_SCHEMACHANGE.ECOMMERCE.USER (
	ID NUMBER(38,0) autoincrement start 1 increment 1 order,
	NAME VARCHAR(100),
	ADDRESS VARCHAR(200)
);
INSERT INTO TEST_SCHEMACHANGE.ECOMMERCE.USER (NAME, ADDRESS)
    VALUES ('Jonas', 'No. 8 Main Stret');